### ISSUE TITLE
USER STORY: Landing Page

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#1]
As a **Site Owner**, I can **display information about the salon** so that **site visitors understand the main purpose of the site**.

## Acceptance Criteria:

* The landing page should have a hero image and hero title which support the site purpose.

## Tasks:

- [x] Create base html template
- [x] Create html structure for the hero content section
- [x] Style hero-content section 
- [x] Create the view code
- [x] Wire up URLs
- [x] Test the completed functionality
