### ISSUE TITLE
USER STORY: Register new account

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#10]
As a **User**, I can **create an account with username and password** so that **I can book appointments**.

## Acceptance Criteria:

* User registration form contains username and password fields.
* Registration process is simple to complete.
* An existing User is redirected to login page.

## Tasks:

- [x] Install and configure the django-allauth library
- [x] Customize Django AllAuth signup.html template 
- [x] Add custom css styles to sign up page
- [x] Test the completed functionality
