### ISSUE TITLE
USER STORY:  Login with username and password

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#11]
As a **Site User**, I can **login with username and password** so that **I can manage my booking requests**.

## Acceptance Criteria:

* User form contains username and password fields.
* If Username exists then the User profile tab is visible on the menu.
* If Username does not exist then the User is redirected to registration page.

## Tasks:

- [x] Customize Django AllAuth login.html template
- [x] Add custom css styles to login page
- [x] Test the completed functionality
