### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#13]
As a **Site User**, I can **securely logout** so that **my information is protected**.

## Acceptance Criteria:

* If a User is logged in then Logout option is made available on the menu.

## Tasks:

- [x] Customize Django AllAuth logout.html template
- [x] Add custom css styles to logout page
- [x] Test the completed functionality
