### ISSUE TITLE
USER STORY: Create booking

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#14]
As an **Authenticated User**, I can **book an appointment** so that **I can attend the salon**.

## Acceptance Criteria:

* Users can submit the booking form if all details are valid.
* Users should be given a constructive advice on how rectify invalid form inputs.
* User should receive a confirmation if the booking was successful.

## Tasks:

- [x] Create a template to render the view
- [x] Create booking form
- [x] Create the view code
- [x] Connect up URLs in the urls.py file
- [x] Test the completed functionality
