### ISSUE TITLE
USER STORY: View booked appointments

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#15]
As an **Authenticated User**, I can **view my bookings** so that **I can check upcoming appointments**.

## Acceptance Criteria:

* Key details of all the existing appointments are displayed.
* Users can view their own appointments only.

## Tasks:

- [x] Create user profile template to render the view
- [x] Create the view code
- [x] Connect up urls file
- [x] Test the completed functionality
