### ISSUE TITLE
USER STORY: Edit booked appointments

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#16]
As an **Authenticated User**, I can **edit my bookings** so that **I can make changes to my appointment if required**.

## Acceptance Criteria:

* Users can change the details of future bookings.
* Users can edit their own appointments only.

## Tasks:

- [x] Create a template to render the edit view
- [x] Create the view code
- [x] Connect up URLs in the urls.py file
- [x] Test the completed functionality
