### ISSUE TITLE
USER STORY: Cancel booked appointments

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#17]
As an **Authenticated User**, I can **cancel my bookings** so that **I can notify the salon if the appointment is no longer required**.

## Acceptance Criteria:

* Users can cancel future bookings.
* Users can cancel their own appointments only.

## Tasks:

- [x] Create the view code to delete bookings
- [x] Connect up URLs in the urls.py file
- [x] Test the completed functionality
