### ISSUE TITLE
USER STORY: Additional section for homepage

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#19]
As a **Site Owner**, I can **display additional information about the salon** so that **I can attract more customers**.

## Acceptance Criteria:

* The home page should contain welcoming text and highlight industry awards
* The home page should contain an image of the salon interior that sets the tone of the business

## Tasks:

- [x] Create html structure for the home content section
- [x] Style home section 
- [x] Test the completed functionality
