### ISSUE TITLE
USER STORY: Call to Action button

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#2]
As a **Business Owner**, I want to **move site visitors towards becoming customers of the salon** so that **I can grow my business**.

## Acceptance Criteria:

* The website should contain a Call to Action button inviting Site Users to book an appointment.

## Tasks:

- [x] Add 'Book Now' button to hero/welcome sections of the home page
- [x] Add url links to 'Book Now' buttons to redirect users to the appointment booking page
- [x] Test the completed functionality
