### ISSUE TITLE
USER STORY: Easy access to booking form

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#21]
As an **Authenticated User**, I can **easily access booking form** so that **I can book an appointment**.

## Acceptance Criteria:

* Booking form should be accessible from any page the User is in and without the need to navigate to another page.

## Tasks:

- [x] Add 'Book Now' button to the navbar on base.html
- [x] Add url link to 'Book Now button to redirect the User to the appointment booking page
- [x] Test the completed functionality
