### ISSUE TITLE
USER STORY: Social Media links

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#3]
As a **As a Business Owner**, I want to **increase awareness about the salon** so that **I can attract new customers**.

## Acceptance Criteria:

* The website should include links to social media.

## Tasks:

- [x] Add Facebook and Instagram font awesome icons to navbar/footer on the base template.
- [x] Style icons to match the overall website style
- [x] Test the completed functionality
