### ISSUE TITLE
USER STORY: Information about salon

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#4]
As a **Site User**, I can **get key information about the salon from the landing page** so that **I can spend less time searching for information**.

## Acceptance Criteria:

* The website should contain opening times, information about location and contact details.

## Tasks:

- [x] Create footer on base template using bootstrap
- [x] Add Font Awesome icons
- [x] Apply custom styling
- [x] Test the completed functionality
