### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#5]
As a **Site User**, I want to be able **to easily navigate throughout the site** so that **I can view relevant content**.

## Acceptance Criteria:

* The navigation bar should stay at the top of the page while scrolling.
* Website navigation bar is present on all pages.

## Tasks:

- [x] Create navbar using Bootstrap
- [x] Customize Bootstrap navbar
- [x] Test the completed functionality
