### ISSUE TITLE
USER STORY: View all appointments

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#7]
As an **Admin User**, I want to be able to **view all appointments** so that **so that I can organise appointments and staff rotas in advance**.

## Acceptance Criteria:

* All the key information about all the appointments should be available to Admin User for viewing in the admin panel.
* Admin User should have the ability to easily filter records to identify upcoming appointments.

## Tasks:

- [x] Build admin panel to display fields from appointment model
- [x] Add search fields to search on first name and phone number
- [x] Add filter on appointment date and status
- [x] Test the completed functionality
