### ISSUE TITLE
USER STORY: Add, modify or cancel appointments Customers' appointments

### ISSUE THREAD

**Issue by ip69719** [ip69719/ci-portfolio-four#9]
As an **Admin User**, I can **add, modify or cancel appointments on Customers' behalf** so that **I can manage salon appointments efficiently**.

## Acceptance Criteria:

* Admin User should be able to login with Username and Password.
* The Admin User can create a new appointment from the admin panel.
* The Admin User can edit existing appointments from the admin panel.
* The Admin User can cancel appointments from the admin panel.

## Tasks:

- [x] Create a Superuser account
- [x] Create a model for the appointment
- [x] Test the completed functionality
